# Introduction to Tensorflow v2

### Import the Tensorflow Framework

In [1]:
import tensorflow as tf

### Printing the versions

In [2]:
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.3.1
Eager execution is: True
Keras version: 2.4.0


### Let's have a look at python variable and tensors

In [3]:
var = 1 
ten = tf.Variable(7) 
another_tensor = tf.Variable([[1, 2],[3, 4]]) 

In [4]:
var, ten, another_tensor

(1,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>)

In [5]:
f1 = tf.Variable(100.6)
print(f1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=100.6>


In [6]:
print(f1.assign(25))
print(f1.dtype)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=25.0>
<dtype: 'float32'>


In [7]:
f2 = tf.Variable(7, dtype = tf.float64)
print(f2.dtype)

<dtype: 'float64'>


In [8]:
constant_var = tf.constant(10)
print(constant_var)

tf.Tensor(10, shape=(), dtype=int32)


In [9]:
constant_var.numpy()

10

In [10]:
tf.rank(another_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [11]:
tf.shape(another_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>

In [12]:
new_tensor = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) 
print(new_tensor.shape)
print(tf.rank(new_tensor))

(2, 2, 3)
tf.Tensor(3, shape=(), dtype=int32)


In [13]:
new_reshape = tf.reshape(new_tensor, [2, 6]) 
recent_reshape = tf.reshape(new_tensor, [1, 12])

In [14]:
print(new_reshape)
print(recent_reshape)

tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]], shape=(2, 6), dtype=float32)
tf.Tensor([[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]], shape=(1, 12), dtype=float32)


In [15]:
print(new_tensor.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [16]:
new_tensor * new_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

In [17]:
new_tensor * 4

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

In [18]:
u = tf.constant([[5, 6, 7]])
v = tf.constant([[8, 9, 0]])
print('Matrix Multiplication - Transpose')
print(tf.matmul(u, tf.transpose(a=v)))

Matrix Multiplication - Transpose
tf.Tensor([[94]], shape=(1, 1), dtype=int32)


In [19]:
int_tensor = tf.cast(ten, dtype=tf.float32)
print(int_tensor)

tf.Tensor(7.0, shape=(), dtype=float32)


# Tensorflow v2 Functions

### Squared Difference Function

In [20]:
#Squared Difference Function
x = [2, 4, 6, 8, 12]
y = 6

#(x-y)*(x-y)
result = tf.math.squared_difference(x, y)
result

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36])>

### Reduce Mean

In [21]:
numbers = tf.constant([[6., 9.], [3., 5.]])
print(numbers)

tf.Tensor(
[[6. 9.]
 [3. 5.]], shape=(2, 2), dtype=float32)


In [22]:
tf.reduce_mean(input_tensor = numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=5.75>

### Mean across columns

In [23]:
#Reduce rows -> Find mean across columns
#(6. + 3.)/2, (9. + 5.)/2
print(tf.reduce_mean(input_tensor = numbers, axis = 0))

tf.Tensor([4.5 7. ], shape=(2,), dtype=float32)


In [24]:
#(6. + 3.)/2, (9. + 5.)/2
print(tf.reduce_mean(input_tensor = numbers, axis = 0, keepdims = True))

tf.Tensor([[4.5 7. ]], shape=(1, 2), dtype=float32)


### Mean across rows

In [25]:
#Reduce columns -> Find mean across rows
#(6. + 9.)/2, (3. + 5.)/2
print(tf.reduce_mean(input_tensor = numbers, axis = 1))

tf.Tensor([7.5 4. ], shape=(2,), dtype=float32)


In [26]:
#(6. + 9.)/2, (3. + 5.)/2
print(tf.reduce_mean(input_tensor = numbers, axis = 1, keepdims = True))

tf.Tensor(
[[7.5]
 [4. ]], shape=(2, 1), dtype=float32)


### Generating normal distribution in a tensor

In [27]:
print(tf.random.normal(shape = (3, 2), mean = 10, stddev = 2, dtype = tf.float32, seed = None, name = None))

tf.Tensor(
[[ 7.8424673 10.017846 ]
 [ 7.9010606 11.682917 ]
 [ 7.7593865 13.132599 ]], shape=(3, 2), dtype=float32)


### Generating uniform distribution in a tensor

In [28]:
tf.random.uniform(shape = (3, 2),  minval = 0, maxval = 1, dtype = tf.float32, seed = None, name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7521368 , 0.33398187],
       [0.5066447 , 0.9244695 ],
       [0.4273026 , 0.23606348]], dtype=float32)>

### Random Seed in Tensorflow

In [29]:
print('Random Seed - 11\n')
tf.random.set_seed(11)
random_1 = tf.random.uniform(shape = (2, 2), maxval = 7, dtype = tf.int32)
random_2 =  tf.random.uniform(shape = (2, 2), maxval = 7, dtype = tf.int32)
print(random_1) 
print(random_2)
print('\n')

print('Random Seed - 12\n')
tf.random.set_seed(12)
random_1 = tf.random.uniform(shape = (2, 2), maxval = 7, dtype = tf.int32)
random_2 =  tf.random.uniform(shape = (2, 2), maxval = 7, dtype = tf.int32)
print(random_1) 
print(random_2)
print('\n')

print('Random Seed - 11\n')
tf.random.set_seed(11)
random_1 = tf.random.uniform(shape = (2, 2), maxval = 7, dtype = tf.int32)
random_2 =  tf.random.uniform(shape = (2, 2), maxval = 7, dtype = tf.int32)
print(random_1) 
print(random_2)

Random Seed - 11

tf.Tensor(
[[4 3]
 [0 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[6 3]
 [6 3]], shape=(2, 2), dtype=int32)


Random Seed - 12

tf.Tensor(
[[0 4]
 [2 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 4]
 [0 1]], shape=(2, 2), dtype=int32)


Random Seed - 11

tf.Tensor(
[[4 3]
 [0 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[6 3]
 [6 3]], shape=(2, 2), dtype=int32)


### Max, Min and Indices

In [30]:
tensor_m = tf.constant([2, 20, 15, 32, 77, 29, -16, -51, 29])
print(tensor_m)
index = tf.argmax(input = tensor_m)
print('Index of max: {}\n'.format(index))
print('Max element: {}'.format(tensor_m[index].numpy()))

tf.Tensor([  2  20  15  32  77  29 -16 -51  29], shape=(9,), dtype=int32)
Index of max: 4

Max element: 77


In [31]:
print(tensor_m)
index = tf.argmin(input = tensor_m)
print('Index of minumum element: {}\n'.format(index))
print('Minimum element: {}'.format(tensor_m[index].numpy()))

tf.Tensor([  2  20  15  32  77  29 -16 -51  29], shape=(9,), dtype=int32)
Index of minumum element: 7

Minimum element: -51


### Tensorflow v2 Graph Function

In [32]:
#Normal Python function
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

#Converting that into Tensorflow Graph function
f2 = tf.function(f1)

x = tf.constant([7., -2.])
y = tf.constant([8., 6.])

#Funtion 1 and function 2 return the same value, but function 2 executes as a TensorFlow graph
assert f1(x,y).numpy() == f2(x,y).numpy()

ans = f1(x,y)
print(ans)

ans = f2(x,y)
print(ans)

tf.Tensor(182.5, shape=(), dtype=float32)
tf.Tensor(182.5, shape=(), dtype=float32)
